### ISSUE TITLE
X-Frame-Options is sameorigin.

### ISSUE THREAD

**Issue by Pacislavek** [torikushiii/discord-widget#1]
`Refused to display 'https://widget.ennead.cc/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

1. **Ask the widget provider**
   If you control `widget.ennead.cc`, you can change the header to allow embedding.

   * Remove `X-Frame-Options`
   * Or set it to `ALLOW-FROM https://yoursite.com` (though not all browsers support this)
   * Or better: use `Content-Security-Policy: frame-ancestors yoursite.com;`

**Comment by torikushiii** [comment]
I’ve fixed it by stripping that header at the Cloudflare edge and adding a proper CSP:

```
Content-Security-Policy: frame-ancestors *;
```

Tested with:

```
curl -I https://widget.ennead.cc/user?id=1081004946872352958
```

and it’s good now, no `X-Frame-Options`, and the widget embeds fine.

**Comment by Pacislavek** [comment]
I've still the same problem 

<img width="2167" height="1208" alt="Image" src="https://github.com/user-attachments/assets/5ed7fefc-25fe-4051-ae73-e52f22a04be7" />

**Comment by torikushiii** [comment]
can you try doing hard refresh (Ctrl+Shift+R) and see if that solve the issue? because I remember Cloudflare cache headers very aggressively .

on another note, I've done some change at the background so it should be fine now.

**Comment by Pacislavek** [comment]
even without refreshing the cache it worked when I came to check.
**thank you for your work!**
